name: 'Genova auto deploy'
description: 'Genova auto deploy'
inputs:
  genova-github-secret-key:
    description: 'genova github secret key'
    required: true
    type: string
  app-domain:
    description: 'app domain'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
