name: 'Genova auto deploy'
description: 'Genova auto deploy'
inputs:
  genova-github-secret-key:
    description: 'genova github secret key'
    required: true
    type: string
  app-domain:
    description: 'app domain'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: fjogeleit/http-request-action@master
        with:
          url: https://genova.console.re-shine.jp/api/v2/github/actions/push
          method: POST
          customHeaders: >-
            {
              "X-GITHUB-SECRET-KEY": "${{secrets.GENOVA_GITHUB_SECRET_KEY}}"
            }
          data: >-
            {
              "repository": "${{github.event.repository.name}}",
              "ref": "${{github.event.ref}}",
              "commit_url": "${{github.event.head_commit.url}}",
              "author": "${{github.event.head_commit.author.username}}",
              "pushed_at": "${{ github.event.repository.pushed_at }} "
            }
