name: 'Genova auto deploy'
description: 'Genova auto deploy'
inputs:
  genova_github_secret_key:
    description: 'genova_github_secret_key'
    required: true
runs:
  using: "composite"
  steps:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: fjogeleit/http-request-action@master
        with:
          url: https://genova.console.re-shine.jp/api/v2/github/actions/push
          method: POST
          GENOVA_GITHUB_SECRET_KEY: 
          customHeaders: >-
            {
              "X-GITHUB-SECRET-KEY": "${{inputs.genova_github_secret_key}}"
            }
          account:
          repository:
          data: >-
            {
              "account": "${{github.event.repository.owner.name}}",
              "repository": "${{github.event.repository.name}}",
              "ref": "${{github.event.ref}}",
              "commit_url": "${{github.event.head_commit.url}}",
              "author": "${{github.event.head_commit.author.username}}",
              "pushed_at": "${{ github.event.repository.pushed_at }} "
            }
